# -*- coding: utf-8 -*-
"""Yfinance_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-6EDrexzq7cGvWpNxobbWQB92t2LoIP

### Getting Historical Data
"""

import yfinance as yf

print('This only deals with stocks listed on NSE & NASDAQ \n')
stock=input('enter a valid stock name : ').strip()


def convert_stock_NS(stock_name):
    NSE_STOCK=f'{stock_name}.NS'
    return NSE_STOCK

ans=input('Is your stock listed on NSE (y/n) : ').strip().lower()
if ans=='y':
    stock=convert_stock_NS(stock)
    stock_data=yf.download(stock,period="5y")
else :
    stock_data=yf.download(stock,period="5y")

stock_ticker = yf.Ticker(stock)
info = stock_ticker.info
stock_name=info.get('shortName', 'N/A')

print(f'\n***************{stock_name}***************\n')


stock_data

"""### Getting Live data"""

import yfinance as yf
import pandas as pd
pd.set_option('display.max_columns', None)

recent_data=yf.download(stock,period="3mo", interval='60m')
print(f'\n***************{stock_name}***************\n')
recent_data

"""### wrapping data & graphing"""

stock_data.columns = stock_data.columns.get_level_values(0)
recent_data.columns = recent_data.columns.get_level_values(0)

stock_data.columns.unique()

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

stock_data['Close'].plot()
plt.show()

recent_data['Close'].plot()
plt.show()
pd.set_option('display.max_columns', None)

from stockstats import wrap
wrapped_data = wrap(stock_data)
wrapped_data.init_all()
#print(wrapped_data)
historical_data = wrapped_data[['close','open', 'high', 'low', 'volume']]
historical_data

"""### News Sentiment Analysis"""

from newsapi import NewsApiClient

api = NewsApiClient(api_key='1727fdcffd8b4c5e936a02fa17ebb381')

data = api.get_everything(q=f'{stock_name}')
articles = data['articles']

# for article in articles:
#     print(article['title'])  # or article['description'], etc.

from langdetect import detect, DetectorFactory
english_articles = []
for article in data['articles']:
    try:
        lang = detect(article['title'] if article['title'] else article['description'])
        if lang == 'en':
            english_articles.append(article)
    except:
        continue
# english_articles

from datetime import datetime
articles = sorted(english_articles, key=lambda x: datetime.strptime(x['publishedAt'], "%Y-%m-%dT%H:%M:%SZ"), reverse=True)

headlines = [article['title'] for article in articles[:15]]
headlines

# from transformers import pipeline

# sentiment_pipeline = pipeline("text-classification", model="mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis")

# full_text = " ".join(headlines)

# result = sentiment_pipeline(full_text[:512])

# print(f"Overall Sentiment for Combined Text: {result[0]['label']}")
# print(f"Confidence: {round(result[0]['score'] * 100, 2)}%")

# print("Article sample timestamp:", articles[0]['publishedAt'], type(articles[0]['publishedAt']), articles[0]['publishedAt'].tzinfo)
# print("Historical index sample:", historical_data.index[0], type(historical_data.index[0]), historical_data.index.tz)

import pandas as pd
from transformers import pipeline

for article in articles:
    article['publishedAt'] = pd.to_datetime(article['publishedAt']).tz_convert('UTC') \
        if pd.to_datetime(article['publishedAt']).tzinfo is not None \
        else pd.to_datetime(article['publishedAt'], utc=True)

if historical_data.index.tz is None:
    historical_data.index = historical_data.index.tz_localize("UTC")

sentiment_pipeline = pipeline("text-classification", model="mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis")

sentiments = []
confidences = []
news_counts = []
weighted_scores = []

label_map = {
    "POSITIVE": 1,
    "NEUTRAL": 0,
    "NEGATIVE": -1
}

for timestamp in historical_data.index:
    relevant_news = [
        article for article in articles
        if article['publishedAt'] <= timestamp
    ]

    news_counts.append(len(relevant_news))

    if relevant_news:
        full_text = " ".join([(a['title'] or '') + ' ' + (a['description'] or '') for a in relevant_news])
        full_text = full_text[:512]
        result = sentiment_pipeline(full_text)[0]

        label = result['label'].upper()
        confidence = round(result['score'], 2)

        sentiments.append(label)
        confidences.append(confidence)
        weighted_scores.append(label_map[label] * confidence)
    else:
        sentiments.append("NEUTRAL")
        confidences.append(None)
        weighted_scores.append(0.0)

# Add columns to DataFrame
historical_data['News_Sentiment'] = sentiments
historical_data['Sentiment_Confidence'] = confidences
historical_data['Num_Relevant_News'] = news_counts
historical_data['Weighted_Sentiment'] = weighted_scores

# Preview

import pandas as pd

print(historical_data[['close', 'News_Sentiment', 'Sentiment_Confidence', 'Num_Relevant_News', 'Weighted_Sentiment']])

last_30 = historical_data.tail(30)

plt.figure(figsize=(12, 6))

# Create a twin axis
fig, ax1 = plt.subplots(figsize=(12, 6))

# Plot stock price on primary y-axis
ax1.plot(last_30.index, last_30['close'], label='Stock Price (Close)', color='blue', marker='o')
ax1.set_xlabel('Date')
ax1.set_ylabel('Stock Price', color='blue')
ax1.tick_params(axis='y', labelcolor='blue')
ax1.tick_params(axis='x', rotation=45)

# Create secondary y-axis for sentiment
ax2 = ax1.twinx()
ax2.plot(last_30.index, last_30['Weighted_Sentiment'], label='Weighted Sentiment', color='green', marker='x')
ax2.set_ylabel('Weighted Sentiment', color='green')
ax2.tick_params(axis='y', labelcolor='green')

# Title and layout
plt.title('Stock Price vs. Weighted Sentiment (Last 30 Entries)')
fig.tight_layout()
plt.show()

"""### Making the data"""

import numpy as np
import pandas as pd
import datetime as dt
from sklearn.preprocessing import MinMaxScaler

mid_prices = ((historical_data['high'] + historical_data['low']) / 2).interpolate().values
split_index = int(len(mid_prices) * 0.8)
train_raw = mid_prices[:split_index]

scaler = MinMaxScaler()
train_scaled = scaler.fit_transform(train_raw.reshape(-1, 1)).flatten()
original_train=train_scaled.copy()
window_size = 100
N = len(train_scaled)

std_avg_predictions = []
mse_errors = []
std_avg_dates = []

for i in range(window_size, N):
    prediction = np.mean(train_scaled[i - window_size:i])
    std_avg_predictions.append(prediction)

    mse_errors.append((prediction - train_scaled[i]) ** 2)

    if i < len(historical_data):
        date = historical_data.index[i]
    else:
        last_date = pd.to_datetime(historical_data.index[-1])
        date = last_date + dt.timedelta(days=i - len(historical_data) + 1)
    std_avg_dates.append(date)

predictions_actual = scaler.inverse_transform(np.array(std_avg_predictions).reshape(-1, 1)).flatten()
true_actual = scaler.inverse_transform(train_scaled[window_size:].reshape(-1, 1)).flatten()

mse_actual = 0.5 * np.mean((predictions_actual - true_actual) ** 2)
print(f"MSE in actual price scale: {mse_actual:.2f}")

import matplotlib.pyplot as plt

plt.figure(figsize=(18, 9))
plt.plot(original_train, label='True Mid Price (Scaled)', color='blue')
plt.plot(range(window_size, len(original_train)), std_avg_predictions, label='SMA on EMA Prediction', color='orange')
plt.xlabel('Time Step')
plt.ylabel('Mid Price (Scaled)')
plt.title('Standard Averaging on EMA-Smoothened Data')
plt.legend()
plt.show()

N = len(train_scaled)
decay = 0.5

run_avg_predictions = []
run_avg_dates = []
mse_errors = []

running_mean = train_scaled[0]
run_avg_predictions.append(running_mean)

for i in range(1, N):
    running_mean = running_mean * decay + (1.0 - decay) * train_scaled[i - 1]
    run_avg_predictions.append(running_mean)

    if i < len(historical_data):
        date = historical_data.index[i]
    else:
        last_date = pd.to_datetime(historical_data.index[-1])
        date = last_date + dt.timedelta(days=i - len(historical_data) + 1)
    run_avg_dates.append(date)

predictions_actual = scaler.inverse_transform(np.array(run_avg_predictions[1:]).reshape(-1, 1)).flatten()
true_actual = scaler.inverse_transform(train_scaled[1:].reshape(-1, 1)).flatten()

mse_actual = 0.5 * np.mean((predictions_actual - true_actual) ** 2)
print(f"MSE error for EMA averaging : {mse_actual:.2f}")

import matplotlib.pyplot as plt

plt.figure(figsize=(15, 6))

plt.plot(train_scaled, label='True Mid Price (Scaled)', color='blue', linewidth=1.5)

plt.plot(range(1, len(run_avg_predictions)), run_avg_predictions[1:],
         label='EMA Predictions (Decay=0.5)', color='orange', linewidth=2)

if len(run_avg_dates) == len(run_avg_predictions) - 1:
    plt.xticks(ticks=np.linspace(0, len(run_avg_dates)-1, 10, dtype=int),
               labels=[run_avg_dates[i].strftime('%Y-%m-%d') for i in np.linspace(0, len(run_avg_dates)-1, 10, dtype=int)],
               rotation=45)

plt.title('EMA vs True Scaled Mid Price')
plt.xlabel('Time')
plt.ylabel('Scaled Mid Price')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
import matplotlib.pyplot as plt

features = historical_data[['open', 'high', 'low', 'volume','Weighted_Sentiment']].values
target = historical_data[['close']].values

train_size = int(len(features) * 0.8)
X_train_raw, X_test_raw = features[:train_size], features[train_size:]
y_train_raw, y_test_raw = target[:train_size], target[train_size:]

scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()

X_train_scaled = scaler_X.fit_transform(X_train_raw)
X_test_scaled = scaler_X.transform(X_test_raw)

y_train_scaled = scaler_y.fit_transform(y_train_raw)
y_test_scaled = scaler_y.transform(y_test_raw)

def create_sequences(X, y, window_size):
    X_seq, y_seq = [], []
    for i in range(window_size, len(X)):
        X_seq.append(X[i - window_size:i])
        y_seq.append(y[i])
    return np.array(X_seq), np.array(y_seq)

window_size = 60
X_train_seq, y_train_seq = create_sequences(X_train_scaled, y_train_scaled, window_size)
X_test_seq, y_test_seq = create_sequences(X_test_scaled, y_test_scaled, window_size)
model = Sequential([
    LSTM(64, return_sequences=False, input_shape=(X_train_seq.shape[1], X_train_seq.shape[2])),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse')
model.summary()

history = model.fit(X_train_seq, y_train_seq, epochs=18, batch_size=32, validation_data=(X_test_seq, y_test_seq), verbose=1)

predicted_scaled = model.predict(X_test_seq)
predicted = scaler_y.inverse_transform(predicted_scaled)
y_true = scaler_y.inverse_transform(y_test_seq)

plt.figure(figsize=(12, 6))
plt.plot(y_true, label='True Closing Price')
plt.plot(predicted, label='Predicted Closing Price')
plt.title('LSTM Multivariate Prediction')
plt.xlabel('Time Step')
plt.ylabel('Price')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Flatten predictions and actual values
y_true_flat = y_true.flatten()
predicted_flat = predicted.flatten()

# Regression metrics
mae = mean_absolute_error(y_true_flat, predicted_flat)
mse = mean_squared_error(y_true_flat, predicted_flat)
rmse = np.sqrt(mse)
mape = np.mean(np.abs((y_true_flat - predicted_flat) / y_true_flat)) * 100
r2 = r2_score(y_true_flat, predicted_flat)

# Directional Accuracy
actual_direction = np.sign(np.diff(y_true_flat))
predicted_direction = np.sign(np.diff(predicted_flat))
directional_accuracy = np.mean(actual_direction == predicted_direction) * 100

print("===== LSTM Test Set Evaluation =====")
print(f"MAE:                 {mae:.4f}")
print(f"RMSE:                {rmse:.4f}")
print(f"MAPE:                {mape:.2f}%")
print(f"R²:                  {r2:.4f}")
print(f"Directional Accuracy:{directional_accuracy:.2f}%")

